spring:
  datasource:
    hikari:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://127.0.0.1:3306/test
      username: root
      password: root

  #
  #  jpa:
  #    show-sql: true

  #spring:
  #  datasource:
  #    url: jdbc:mysql://127.0.0.1:3306/test
  #    username: root
  #    password: root
  #    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true